### ISSUE TITLE
useHooks

### ISSUE THREAD

**Issue by behnood-eghbali** [behnood-eghbali/messaging-app#6]
Use hooks as a global state manager for this app. Use functional components instead of class components.

**Comment by faabiopontes** [comment]
May I help with that?

**Comment by ruhci28** [comment]
Hii @behnood-eghbali  can i change the contact.js and message.js to functional component.?

**Comment by behnood-eghbali** [comment]
@ruhci28 Sure. :) Why not? ;)

**Comment by behnood-eghbali** [comment]
@ruhci28 Sure. :) Why not? ;)

**Comment by faabiopontes** [comment]
@ruhci28 I will not take those then

**Comment by ruhci28** [comment]
yeah sure @faabiopontes

**Comment by Guilh** [comment]
I'd love to take some on as well if there's room. :)

**Comment by behnood-eghbali** [comment]
@Guilh Ok :) What are you suggesting?

**Comment by faabiopontes** [comment]
@behnood-eghbali maybe do a checklist expliciting everything that can be changed (all components, all hooks) and then each can take one

**Comment by behnood-eghbali** [comment]
@faabiopontes Good point! :)

**Comment by behnood-eghbali** [comment]
@faabiopontes @ruhci28 @Guilh Everything can be changed. So each of you can take one. The goal is refactoring and enhancing the code.

**Comment by behnood-eghbali** [comment]
@faabiopontes You can set the global state with hooks and change the structure. @Guilh You can change the components.

**Comment by faabiopontes** [comment]
@behnood-eghbali will do

**Comment by yigitcukuren** [comment]
I have made some changes, please see #9.

**Comment by felix-chin** [comment]
I would love to help with this as well, if there's still work to go around

**Comment by behnood-eghbali** [comment]
@yigitcukuren Thank you! :)

**Comment by behnood-eghbali** [comment]
@felix-chin I'm so sorry but I have to close this issue. :( If there's any changes or issues I'll let you know. Thank you! ;)
